SELECT 
    DM.FAT_INCASSI.INC_DATA,
    DM.FAT_INCASSI.PDV_KEY,
    DM.DIM_ANA_PDV.PDV_RAPP_COD,
    DM.FAT_INCASSI.INC_VALORE,
    DM.FAT_INCASSI.INC_BATTUTE_TOT
FROM 
    DM.FAT_INCASSI
INNER JOIN DM.DIM_ANA_PDV 
ON DM.FAT_INCASSI.PDV_KEY = DM.DIM_ANA_PDV.PDV_KEY
WHERE DM.DIM_ANA_PDV.PDV_RAPP_COD = 'C';


SELECT 
    cco.CCO_COD,
    TO_CHAR(TRUNC(inc.INC_DATA), 'DD-MM-YYYY') AS DATA_GIORNALIERA,
    inc.PDV_KEY,
    MAX(inc.CLASS_REP_COD),
    SUM(inc.INC_VALORE) AS INC_VALORE,
    SUM(inc.INC_BATTUTE_TOT) AS INC_BATTUTE_TOT
FROM (
    SELECT 
        DM.FAT_INCASSI.INC_DATA,
        DM.FAT_INCASSI.PDV_KEY,
        DM.FAT_INCASSI.CLASS_REP_COD,
        DM.DIM_ANA_PDV.PDV_RAPP_COD,
        DM.FAT_INCASSI.INC_VALORE,
        DM.FAT_INCASSI.INC_BATTUTE_TOT
    FROM 
        DM.FAT_INCASSI
    INNER JOIN DM.DIM_ANA_PDV 
    ON DM.FAT_INCASSI.PDV_KEY = DM.DIM_ANA_PDV.PDV_KEY
    WHERE DM.DIM_ANA_PDV.PDV_RAPP_COD = 'C'
) inc
LEFT JOIN (
    SELECT
        PDV_KEY, 
        CLASS_REP_COD, 
        MAX(CCO_COD) AS CCO_COD
    FROM DM.DIM_ANA_CCO_REP
    GROUP BY PDV_KEY, CLASS_REP_COD
) cco
    ON inc.PDV_KEY = cco.PDV_KEY 
    AND inc.CLASS_REP_COD = cco.CLASS_REP_COD
WHERE 
    inc.INC_DATA >= TO_TIMESTAMP('2025-02-20', 'YYYY-MM-DD') 
    AND inc.INC_DATA < TO_TIMESTAMP('2025-02-21', 'YYYY-MM-DD')
    AND inc.PDV_KEY = 638
GROUP BY 
    cco.CCO_COD,
    TRUNC(inc.INC_DATA),
    inc.PDV_KEY;

