SELECT
    TO_CHAR(INC_DATA, 'YYYY-MM-DD HH24:MI:SS') AS day,
    PDV_COD AS pdvcode,
    CCO_COD AS ccocode,
    INC_VALORE AS sales,        
    INC_BATTUTE_TOT AS tickets
    FROM DM.FAT_INCASSI
INNER JOIN 
    DM.DIM_ANA_PDV ON DM.FAT_INCASSI.PDV_KEY = DM.DIM_ANA_PDV.PDV_KEY
INNER JOIN 
    DM.DIM_ANA_CCO_REP ON DM.FAT_INCASSI.PDV_KEY = DM.DIM_ANA_CCO_REP.PDV_KEY
WHERE 
    INC_DATA >= TO_DATE('2025-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
FETCH FIRST 10 ROWS ONLY;

SELECT * FROM DM.fat_incassi;



