SELECT 
    cco.CCO_COD,
    TO_CHAR(TRUNC(inc.INC_DATA)) AS DATA_GIORNALIERA,
    inc.PDV_KEY,
    SUM(inc.INC_VALORE) AS INC_VALORE,
    SUM(inc.INC_BATTUTE_TOT) AS INC_BATTUTE_TOT
FROM 
    DM.FAT_INCASSI inc
LEFT JOIN (
    SELECT 
        PDV_KEY, 
        CLASS_REP_COD, 
        MAX(CCO_COD) AS CCO_COD
    FROM DM.DIM_ANA_CCO_REP
    GROUP BY PDV_KEY, CLASS_REP_COD
) cco
    ON inc.PDV_KEY = cco.PDV_KEY 
    AND inc.CLASS_REP_COD = cco.CLASS_REP_COD
WHERE 
    inc.INC_DATA >= TO_TIMESTAMP('2025-02-20', 'YYYY-MM-DD') 
    AND inc.INC_DATA < TO_TIMESTAMP('2025-02-22', 'YYYY-MM-DD')
    AND inc.PDV_KEY = 638
GROUP BY 
    cco.CCO_COD,
    TRUNC(inc.INC_DATA),
    inc.PDV_KEY;

