SELECT TO_CHAR(INC_DATA, 'YYYY-MM-DD HH24:MI:SS') AS INC_DATA,
PDV_KEY,
CLASS_REP_COD,
INC_VALORE,
INC_GESTIONE,
INC_POL_COMM,
TO_CHAR(INC_DATA_ULTMOD, 'YYYY-MM-DD HH24:MI:SS') AS INC_DATA_ULTMOD,
TO_CHAR(INC_DATA_INS, 'YYYY-MM-DD HH24:MI:SS') AS INC_DATA_INS,
CLASS_REP_DESC,
KAL_MESG,
KAL_SETG,
INC_PRESENZE_REP,
INC_BATTUTE_TOT
FROM DM.FAT_INCASSI
FETCH FIRST 30 ROWS ONLY;

SELECT * FROM DM.fat_incassi;



