
SELECT 
    DM.FAT_INCASSI.INC_DATA,
    DM.FAT_INCASSI.PDV_KEY,
    DM.DIM_ANA_PDV.PDV_RAPP_COD,
    DM.FAT_INCASSI.INC_VALORE,
    DM.FAT_INCASSI.INC_BATTUTE_TOT
FROM 
    DM.FAT_INCASSI
INNER JOIN DM.DIM_ANA_PDV 
ON DM.FAT_INCASSI.PDV_KEY = DM.DIM_ANA_PDV.PDV_KEY
WHERE DM.DIM_ANA_PDV.PDV_RAPP_COD = 'C';


SELECT 
    TO_CHAR(TRUNC(inc.INC_DATA), 'DD-MM-YYYY') AS INC_DATA,
    CAST(inc.PDV_COD AS INT),
    cco.CCO_COD,  
    SUM(inc.INC_VALORE) AS INC_VALORE
FROM (
    SELECT 
        DM.FAT_INCASSI.INC_DATA,
        DM.DIM_ANA_PDV.PDV_COD,
        DM.DIM_ANA_PDV.PDV_KEY,
        DM.FAT_INCASSI.CLASS_REP_COD,
        DM.DIM_ANA_PDV.PDV_RAPP_COD,
        DM.FAT_INCASSI.INC_VALORE
    FROM 
        DM.FAT_INCASSI
    INNER JOIN DM.DIM_ANA_PDV 
    ON DM.FAT_INCASSI.PDV_KEY = DM.DIM_ANA_PDV.PDV_KEY
    WHERE DM.DIM_ANA_PDV.PDV_RAPP_COD = 'C'
) inc
LEFT JOIN (
    SELECT
        PDV_KEY, 
        CLASS_REP_COD, 
        MAX(CCO_COD) AS CCO_COD
    FROM DM.DIM_ANA_CCO_REP
    GROUP BY PDV_KEY, CLASS_REP_COD
) cco
    ON inc.PDV_KEY = cco.PDV_KEY 
    AND inc.CLASS_REP_COD = cco.CLASS_REP_COD
WHERE 
    inc.INC_DATA >= TO_TIMESTAMP('20-02-2025', 'DD-MM-YYYY') 
    AND inc.INC_DATA < TO_TIMESTAMP('22-02-2025', 'DD-MM-YYYY')
    AND cco.CCO_COD IS NOT NULL
    -- AND inc.PDV_COD = 423 -- TMP
GROUP BY
    inc.PDV_COD,
    cco.CCO_COD,
    TRUNC(inc.INC_DATA)
ORDER BY
    INC_DATA DESC;


-- CACCIA VECT PDV_COD
SELECT 
    CAST(inc.PDV_COD AS INT)
FROM (
    SELECT 
        DM.FAT_INCASSI.INC_DATA,
        DM.DIM_ANA_PDV.PDV_COD,
        DM.DIM_ANA_PDV.PDV_KEY,
        DM.FAT_INCASSI.CLASS_REP_COD,
        DM.DIM_ANA_PDV.PDV_RAPP_COD,
        DM.FAT_INCASSI.INC_VALORE
    FROM 
        DM.FAT_INCASSI
    INNER JOIN DM.DIM_ANA_PDV 
    ON DM.FAT_INCASSI.PDV_KEY = DM.DIM_ANA_PDV.PDV_KEY
    WHERE DM.DIM_ANA_PDV.PDV_RAPP_COD = 'C'
) inc
LEFT JOIN (
    SELECT
        PDV_KEY, 
        CLASS_REP_COD, 
        MAX(CCO_COD) AS CCO_COD
    FROM DM.DIM_ANA_CCO_REP
    GROUP BY PDV_KEY, CLASS_REP_COD
) cco
    ON inc.PDV_KEY = cco.PDV_KEY 
    AND inc.CLASS_REP_COD = cco.CLASS_REP_COD
WHERE 
    inc.INC_DATA >= TO_TIMESTAMP('20-02-2025', 'DD-MM-YYYY') 
    AND inc.INC_DATA < TO_TIMESTAMP('22-02-2025', 'DD-MM-YYYY')
    AND cco.CCO_COD IS NOT NULL
GROUP BY
    inc.PDV_COD;